### ISSUE TITLE
Reorganize code of index.html and indent accordingly

### ISSUE THREAD

**Issue by TuhinKundu** [TuhinKundu/CSE-2015-19-website#5]

**Comment by mbtamuli** [comment]
I want to work on this.

**Comment by mbtamuli** [comment]
What about the commented code? Should that be removed or should it be kept as it is?

**Comment by TuhinKundu** [comment]
Commented code has to be removed. Plus I have already received 2 PRs which are not complete. Please complete before they edit the PRs.

**Comment by andela-araimi** [comment]
Please merge the PR, it has been completed

**Comment by MADPT** [comment]
#10 refactor index-html
